#ifndef SYNTAGRUSPARSER_GLOBAL_H
#define SYNTAGRUSPARSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SYNTAGRUSPARSER_LIBRARY)
#  define SYNTAGRUSPARSERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SYNTAGRUSPARSERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SYNTAGRUSPARSER_GLOBAL_H
