#ifndef RUTEXTPARSER_EXTENSIONS_GLOBAL_H
#define RUTEXTPARSER_EXTENSIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RUTEXTPARSER_EXTENSIONS_LIBRARY)
#  define RUTEXTPARSER_EXTENSIONSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RUTEXTPARSER_EXTENSIONSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RUTEXTPARSER_EXTENSIONS_GLOBAL_H
