#ifndef CYK_SYNTACTICAL_ANALYZER_GLOBAL_H
#define CYK_SYNTACTICAL_ANALYZER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CYK_SYNTACTICAL_ANALYZER_LIBRARY)
#  define CYK_SYNTACTICAL_ANALYZERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CYK_SYNTACTICAL_ANALYZERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CYK_SYNTACTICAL_ANALYZER_GLOBAL_H
