#ifndef SYNTAGRUS_PARSER_GLOBAL_H
#define SYNTAGRUS_PARSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SYNTAGRUS_PARSER_LIBRARY)
#  define SYNTAGRUS_PARSERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SYNTAGRUS_PARSERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SYNTAGRUS_PARSER_GLOBAL_H
