#ifndef CYKANALYZER_GLOBAL_H
#define CYKANALYZER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CYKANALYZER_LIBRARY)
#  define CYKANALYZERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CYKANALYZERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CYKANALYZER_GLOBAL_H
